from django.urls import path
from . import views
urlpatterns = [
    path('', views.Admin_Homepage, name='Home'),
    #path('Chart', views.Admin_Chart, name='Chart'),
    #path('Form', views.Admin_Form, name='Form'),
    path('Login', views.Admin_Login, name='Login'),
    #path('Register', views.Admin_Register, name='Register'),
    path('Error', views.Admin_Error_404, name='Error'),
    #path('Table', views.Admin_Table, name='Table'),
    path('Error-500', views.Admin_Error_500, name="Error-500"),
    path('Chat', views.Chat, name="Category"),
    path('Category', views.Admin_Category, name="Category"),
    path('Category_form', views.Category_form, name="Add Category"),
    path('Category/inserted', views.Category_Add_Process,
         name="Category Add Process"),
    path('Category/edit/<int:id>', views.Category_Edit, name="Category Edit"),
    path('Category/update', views.Category_Update, name="Category Update"),
    path('Category/delete/<int:id>', views.Category_Delete, name="Category Delete"),
    path('Company/inserted', views.Company_Add_Process,
         name="Comapany Add Process"),
    path('Company', views.Admin_Company, name="Company"),
    path('Company/edit/<int:id>', views.Company_Edit, name="Company Edit"),
    path('Company/update', views.Company_Update, name="Company Update"),
    path('Company/delete/<int:id>', views.Company_Delete, name="Company Delete"),
    path('Job', views.Admin_Job, name="Job"),
    path('Job/delete/<int:id>', views.Job_Delete, name="Job Delete"),
    path('JobSeeker/inserted', views.JobSeeker_Add_Process,
         name="JobSeeker Add Process"),
    path('JobSeekers', views.Admin_JobSeekers, name="Job Seekers"),
    path('JobSeekers/edit/<int:id>', views.JobSeeker_Edit, name="JobSeekers Edit"),
    path('JobSeekers/update', views.JobSeeker_Update, name="JobSeekers Update"),
    path('JobSeeker/delete/<int:id>',views.JobSeeker_Delete, name="JobSeeker Delete"),
    path('Payment', views.Admin_Payment, name="Payment"),
    path('Applied', views.Admin_Applied, name="Applied"),
    path('Company_form', views.Company_form, name="Add Company"),
    path('Seeker_form', views.Seeker_form, name="Add Job Seeker"),
    path('logout', views.logout, name="Add Job Seeker2"),
    
]